const productos = [
    {nombre: "-------------REMERAS-------------",
     precio: 4000,
     imagen: "./img/remera1.jpg",
     categoria: "remera",
     id: "remera"
    },
    {nombre: "-----------PANTALONES----------",
    precio: 13000,
    imagen: "./img/pantalon1.jpg",
    categoria: "pantalon",
    id: "pantalon"
    },
    {nombre: "-------------ABRIGOS--------------",
    precio: 24000,
    imagen: "./img/campera1.jpg",
    categoria: "campera",
    id: "campera"
    },
    {nombre: "-----------ZAPATILLAS-----------",
    precio: 26000,
    imagen: "./img/zapatilla1.jpg",
    categoria: "zapatilla",
    id: "zapatilla"
    },
    {nombre: "-----------PANTALONES----------",
    precio: 14000,
    imagen: "./img/pantalon2.jpg",
    categoria: "pantalon",
    id: "pantalon01"
    },
    {nombre: "-------------ABRIGOS-------------",
    precio: 22000,
    imagen: "./img/campera2.jpg",
    categoria: "campera",
    id: "campera01"
    },
    {nombre: "-----------ZAPATILLAS-----------",
    precio: 22000,
    imagen: "./img/zapatilla2.jpg",
    categoria: "zapatilla01",
    id: "zapatilla01"
    },
    {nombre: "-------------REMERAS-------------",
    precio: 5000,
    imagen: "./img/remera2.jpg",
    categoria: "remera",
    id: "remera01"
    },
    {nombre: "-----------PANTALONES----------",
    precio: 14000,
    imagen: "./img/pantalon3.jpg",
    categoria: "pantalon",
    id: "pantalon02"
    },
    {nombre: "-------------ABRIGOS-------------",
    precio: 22000,
    imagen: "./img/campera3.jpg",
    categoria: "campera",
    id: "campera02"
    },
    {nombre: "-----------ZAPATILLAS-----------",
    precio: 22000,
    imagen: "./img/zapatilla2.jpg",
    categoria: "zapatilla",
    id: "zapatilla01"
    },
    {nombre: "-------------ABRIGOS-------------",
    precio: 5000,
    imagen: "./img/campera4.jpg",
    categoria: "campera",
    id: "campera03"
    },
    {nombre: "-----------PANTALONES----------",
    precio: 14000,
    imagen: "./img/pantalon4.jpg",
    categoria: "pantalon",
    id: "pantalon03"
    },
    {nombre: "-------------ABRIGOS-------------",
    precio: 22000,
    imagen: "./img/campera3.jpg",
    categoria: "campera",
    id: "campera"
    },
    {nombre: "-----------ZAPATILLAS-----------",
    precio: 22000,
    imagen: "./img/zapatilla2.jpg",
    categoria: "zapatilla",
    id: "zapatilla"
    },
    {nombre: "-------------REMERAS-------------",
    precio: 5000,
    imagen: "./img/remera2.jpg",
    categoria: "remera",
    id: "remera04"
    },
    {nombre: "-----------PANTALONES----------",
    precio: 14000,
    imagen: "./img/pantalon4.jpg",
    categoria: "pantalon",
    id: "pantalon"
    },
    {nombre: "-------------ABRIGOS-------------",
    precio: 22000,
    imagen: "./img/campera3.jpg",
    categoria: "campera",
    id: "campera"
    },
    {nombre: "-----------ZAPATILLAS-----------",
    precio: 22000,
    imagen: "./img/zapatilla2.jpg",
    categoria: "zapatilla",
    id: "zapatilla"
    },
    {nombre: "-------------REMERAS-------------",
    precio: 5000,
    imagen: "./img/remera2.jpg",
    categoria: "remera",
    id: "remera"
    },
    {nombre: "-------------REMERAS-------------",
    precio: 5000,
    imagen: "./img/remera2.jpg",
    categoria:"remera",
        id: "remera"
    },
];